PREFIX c0x: <urn:c0x:>
SELECT ?resource WHERE {
  {
    ?resource c0x:type "Procedure" .
    ?resource c0x:code "73761001" .
  }
  UNION
  {
    ?resource c0x:type "Procedure" .
    ?resource c0x:code "444783004" .
  }
  UNION
  {
    ?resource c0x:type "Observation" .
    ?resource c0x:code "77353-1" .
  }
  UNION
  {
    ?resource c0x:type "Observation" .
    ?resource c0x:code "58453-2" .
  }
}
LIMIT 600
